### ISSUE TITLE
Deprecated Functionality: Optional parameter declared before required parameter 

### ISSUE THREAD

**Issue by richiardc** [NOOE-Phygital-Stores/M2-Connector#15]
Hi, 
I would like to notice to you that there are problem of compatibility with PHP 8.1 and using your module with Magento 2.4.4-p2 (commerce cloud) we encountered in that error:

The command "php ./bin/magento setup:di:compile --ansi --no-interaction" failed. Deprecated Functionality: Optional parameter $handlers declared before required parameter $configData is implicitly treated as a required parameter in /app/vendor/nooe/module-connector/Logger/Logger.php on line 34
    W: 
    W: In Processor.php line 129:
    W:                                                                                
    W:   The command "php ./bin/magento setup:di:compile --ansi --no-interaction" fa  
    W:   iled. Deprecated Functionality: Optional parameter $handlers declared befor  
    W:   e required parameter $configData is implicitly treated as a required parame  
    W:   ter in /app/vendor/nooe/module-connector/Logger/Logger.php on line 34        
    W:                                                                                
    W: 
    W: In CompileDi.php line 73:
    W:                                                                                
    W:   The command "php ./bin/magento setup:di:compile --ansi --no-interaction" fa  
    W:   iled. Deprecated Functionality: Optional parameter $handlers declared befor  
    W:   e required parameter $configData is implicitly treated as a required parame  
    W:   ter in /app/vendor/nooe/module-connector/Logger/Logger.php on line 34        
    W:                                                                                
    W: 
    W: In Shell.php line 86:
    W:                                                                                
    W:   The command "php ./bin/magento setup:di:compile --ansi --no-interaction" fa  
    W:   iled. Deprecated Functionality: Optional parameter $handlers declared befor  
    W:   e required parameter $configData is implicitly treated as a required parame  
    W:   ter in /app/vendor/nooe/module-connector/Logger/Logger.php on line 34

**Comment by nghelo** [comment]
Fixed on last release 1.0.8
