### ISSUE TITLE
report.ERROR: Area code is already set

### ISSUE THREAD

**Issue by richiardc** [NOOE-Phygital-Stores/M2-Connector#21]
Hi,
I would like to notice to you that there are a big error in your file app/code/Nooe/Connector/Console/Command/Sync.php. You have initialized area code in the costructor body but that implementation is wrong ad causes the Area code is already set error that stops also messages queue management.

The solution is to move that operation at the beginning of execute method:

```
...
/**
	 * {@inheritdoc}
	 */
	protected function execute(InputInterface $input, OutputInterface $output)
	{
        $this->state->setAreaCode('adminhtml');
        ...

**Comment by nghelo** [comment]
Fixed in 1.1.0 release
